#
# Copyright zhigui Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  fabsdk:
    external:
      name: net_byfn

services:
  fabric-grpc:
    container_name: 57suo-back-end
    image: harbor.zhigui.com/57suo/back-end:latest
    ports:
      - 8080:8080
    volumes:
      - ./conf:/go/src/fabric-byzantine/conf
      - ./channel-artifacts:/go/src/fabric-byzantine/channel-artifacts
      - ./crypto-config:/go/src/fabric-byzantine/crypto-config
      - /tmp/fabric-byzantine-logs:/go/src/fabric-byzantine/logs
    networks:
      - fabsdk